version: '3.1'
services:
  scd_influxdb:
    image: influxdb:2
#    volumes:
#      - /mnt/influxdb/data:/var/lib/influxdb2:rw
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=sa
      - DOCKER_INFLUXDB_INIT_PASSWORD=ComeToSchool1367
      - DOCKER_INFLUXDB_INIT_ORG=IOT
      - DOCKER_INFLUXDB_INIT_BUCKET=IOT_SCD_PROJECT
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=MyInitialAdminToken0==
    ports:
      - 8086:8086
  scd-influxdb-dal:
    image: influx_db_access
    restart: always
    ports:
      - 50030:50030
    environment:
      - environment=running
      - SCD_INFLUXDB_DAL_ORG=IOT
      - SCD_INFLUXDB_DAL_INFLUXDB_URL=http://scd_influxdb:8086
      - SCD_INFLUXDB_DAL_INFLUXDB_TOCKEN=MyInitialAdminToken0==
      - SCD_INFLUXDB_DAL_INFLUXDB_BUCKET=IOT_SCD_PROJECT
      - IP_ADDRESS=scd-influxdb-dal
      - IP_PORT=50030
      - service_catalog=http://service_catalog:50010
    depends_on:
      - "scd_influxdb"
  scd-mosquitto:
    image: scd-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "1893:1893"
      - "9001:9001"
#    volumes:
#      - ./mosquitto:/etc/mosquitto
#      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  scd-relational-database-postgress:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ComeToSchool1367
  scd_relational_database_dao:
    image: scd_postgress_dao
    restart: always
    ports:
      - 50000:50000
    environment:
      RD_database_name: postgres
      RD_user_name: postgres
      environment: running
      RD_user_password: ComeToSchool1367
      RD_host: scd-relational-database-postgress
      RD_port_number: 5432
      RD_time_out: 30
      IP_PORT: 50000
      IP_ADDRESS: scd_relational_database_dao
    depends_on:
      - "scd-relational-database-postgress"
  service_catalog:
    image: service_catalog
    restart: always
    ports:
      - 50010:50010
    environment:
      IP_PORT: 50010
      IP_ADDRESS: 0.0.0.0
      scd_relational_database_dao: http://scd_relational_database_dao:50000
      environment: RUNNING
    depends_on:
      - "scd_relational_database_dao"
      - "scd-relational-database-postgress"
  scd_reporting:
    image:  scd_reporting
    restart: always
    ports:
      - 50070:50070
    environment:
      IP_PORT: 50070
      IP_ADDRESS: scd_reporting
      service_catalog: http://service_catalog:50010
    depends_on:
      - "service_catalog"
      - "scd_relational_database_dao"
      - "scd-influxdb-dal"
      - "scd_influxdb"
  resource_catalog:
    image: resource_catalog
    restart: always
    ports:
      - 60090:60090
    environment:
      IP_PORT: 60090
      IP_ADDRESS: resource_catalog
      service_catalog: http://service_catalog:50010
    depends_on:
      - "service_catalog"
      - "scd_relational_database_dao"
      - "scd-influxdb-dal"
      - "scd_influxdb"
  scd_notifications:
    image: scd_notifications
    restart: always
    ports:
      - 50110:50110
    environment:
      IP_PORT: 50110
      IP_ADDRESS: scd_notifications
      service_catalog: http://service_catalog:50010
      environment: RUNNING
      mosquitto_url: scd-mosquitto
      mosquitto_port: 1883
    depends_on:
      - "service_catalog"
      - "scd_relational_database_dao"
      - "scd-influxdb-dal"
      - "scd_influxdb"



